export const substationsData = {
    "Andra Pradesh": ["Chilkaluripeta", "GAZUWAKA", "GOOTY", "KADAPA", "KURNOOL", "NAGARJUNSAGAR", "NELLORE", "NP KUNTA", "SRIKAKULAM", "VEMAGIRI", "VIJAYAWADA", "VIZAGHVDC"],
    "Karnataka": ["MUNIRABAD", "RAICHUR", "BANGALORE", "BIDADI", "HASSAN", "HIRIYUR", "KOLAR", "KUDGI", "MADHUGIRI", "MYSORE", "NARENDRA", "PAVAGADA", "YELAHANKA"],
    "Telangana": ["HYDERABAD", "KHAMMAM", "MAHESHWARAM", "NIZAMABAD", "WARRANGAL"],
    "Pondicherry": ["PUDUCHERRY"],
    "Tamil Nadu": ["ARASUR", "DHARMAPURI", "HOSUR", "KALIBANDHAPATU", "KARAIKUDI", "MADRAS", "MADURAI", "NAGAPATTINAM", "PUGALUR", "SALEM", "THIRUNELVELI", "TIRUVALEM", "TRICHY", "TUTICORIN PS", "UDUMALPET"],
    "Kerala": ["KOCHI", "KOZHIKODE", "PALLAKAD", "THIRUVANANTHAPURAM", "TRICHUR", "TRISSUR"]
  };
  